import {
  URL_FOR_PROFILE_ME,
  URL_FOR_TOKEN,
  URL_FOR_AVATAR_PLACEHOLDER,
  URL_FOR_CARDS_PHOTOS,
  URL_FOR_LOGIN,
  URL_FOR_PHOTO_QUERY,
  URL_FOR_USER_QUERY,
  URL_FOR_USER_LIKES_QUERY,
  URL_FOR_USER_PHOTO_LISTING_QUERY,
  URL_FOR_USER_STATISTIC,
  URL_FOR_ERROR_IMAGE,
} from './api';

import {
  INITIONAL_CHARTS_CONFIGS,
  CHARTS_CATEGORIES,
  CHART_CONFIG,
} from './chart';

export {
  URL_FOR_PROFILE_ME,
  URL_FOR_TOKEN,
  URL_FOR_AVATAR_PLACEHOLDER,
  URL_FOR_CARDS_PHOTOS,
  URL_FOR_LOGIN,
  URL_FOR_PHOTO_QUERY,
  URL_FOR_USER_QUERY,
  URL_FOR_USER_LIKES_QUERY,
  URL_FOR_USER_PHOTO_LISTING_QUERY,
  URL_FOR_USER_STATISTIC,
  INITIONAL_CHARTS_CONFIGS,
  CHARTS_CATEGORIES,
  CHART_CONFIG,
  URL_FOR_ERROR_IMAGE,
};
